In [3]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [ ]:
print("it works")

it works

In [ ]:
print("it works")

it works

In [5]:
import pandas as pd

df = pd.read_csv("../data/ethiopia.csv")
df.head()

ModuleNotFoundError: No module named 'pandas'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [2]:
import sys
print(sys.executable)

c:\Users\HP\Desktop\climate-challenge-week0\.venv\Scripts\python.exe

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Setup is working ✔️")

Setup is working ✔️

In [4]:
import pandas as pd

df = pd.read_csv("your_file.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'your_file.csv'

In [5]:
import pandas as pd

data = {
    "name": ["A", "B", "C"],
    "age": [20, 21, 22]
}

df = pd.DataFrame(data)
df

  name  age
0    A   20
1    B   21
2    C   22

In [6]:
df.head()

  name  age
0    A   20
1    B   21
2    C   22

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [8]:

df.describe()

        age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

In [9]:
df["age"]

0    20
1    21
2    22
Name: age, dtype: int64

In [10]:
df

  name  age
0    A   20
1    B   21
2    C   22

In [11]:
df.head()

  name  age
0    A   20
1    B   21
2    C   22

In [12]:
df.tail()

  name  age
0    A   20
1    B   21
2    C   22

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [14]:
df[["name", "age"]]

  name  age
0    A   20
1    B   21
2    C   22

In [15]:
df["age"].mean()

np.float64(21.0)

In [16]:
df["age"].max()

np.int64(22)

In [17]:
df["age"].min()

np.int64(20)

In [18]:
df["age_plus_5"] = df["age"] + 5
df

  name  age  age_plus_5
0    A   20          25
1    B   21          26
2    C   22          27

In [19]:
df[df["age"] > 20]

  name  age  age_plus_5
1    B   21          26
2    C   22          27